name: my_house_design
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.8.4
  shared_preferences: ^2.5.1
  petitparser: ^6.0.2
  carousel_slider: ^5.0.0
  flutter_custom_clippers: ^2.1.0
  http: ^1.3.0
  dio: ^5.8.0+1
  cupertino_icons: ^1.0.8
  provider: ^6.1.4
  google_generative_ai: ^0.4.6
  flutter_markdown: ^0.7.7
  uuid: ^4.5.1
  path_provider: ^2.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_spinkit: ^5.2.1
  image_picker: ^1.1.2
  flutter_bloc: ^9.1.0
  google_sign_in: ^6.3.0
  equatable: ^2.0.5
  flutter_facebook_auth: ^7.1.1
  cached_network_image: ^3.4.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/

